spring:
  config:
    activate:
      on-profile: local
  application:
    name: password-management-service
server:
  port: 8081
  servlet:
    context-path: /experience/customerManagement/partyReferenceDataDirectory
grpc:
  server:
    port: 9090
    address: 0.0.0.0
        
mvc:
pathmatch:
matching-strategy: ant_path_matcher
  
logging:
  level:
    root: INFO
    com.ec: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 

msd.seg.verify.person.api.url: https://localhost:8082/seguridad/v1/cliente/personasnaturales/tiene-ruc

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: password-management-service
server:
  port: 8081
  servlet:
    context-path: /experience/customerManagement/partyReferenceDataDirectory
    
mvc:
pathmatch:
matching-strategy: ant_path_matcher
  
logging:
  level:
    root: INFO
    com.ec: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 

msd.seg.verify.person.api.url: https://${MSD_SEG_VERIFY_PERSON_URL}/seguridad/v1/cliente/personasnaturales/tiene-ruc

---

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: password-management-service
server:
  port: 8081
  servlet:
    context-path: /experience/customerManagement/partyReferenceDataDirectory
    
mvc:
pathmatch:
matching-strategy: ant_path_matcher
  
logging:
  level:
    root: INFO
    com.ec: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 

msd.seg.verify.person.api.url: https://${MSD_SEG_VERIFY_PERSON_URL}/seguridad/v1/cliente/personasnaturales/tiene-ruc

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: password-management-service
server:
  port: 8081
  servlet:
    context-path: /experience/customerManagement/partyReferenceDataDirectory
    
mvc:
pathmatch:
matching-strategy: ant_path_matcher
  
logging:
  level:
    root: INFO
    com.ec: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 

msd.seg.verify.person.api.url: https://${MSD_SEG_VERIFY_PERSON_URL}/seguridad/v1/cliente/personasnaturales/tiene-ruc

